### ISSUE TITLE
Add CD pipeline for Docker Containers

### ISSUE THREAD

**Issue by JBorrow** [simonsobs/librarian#53]
Need x86 containers built through a CD pipeline for running at NERSC>

**Comment by JBorrow** [comment]
There is a Docker `simonsobs` organisation, we need to figure out how to push to that on a version revision.

**Comment by iparask** [comment]
Will do, and I got access to simonsobs docker org. Do you have the permissions to create secrets for this repo?

**Comment by JBorrow** [comment]
Yep!
